#include <stdio.h>
#include "node.h"

/* Function: decrypt
 * =================
 * The main function for huffman decrypting.
 * It decrypts the huffman code information contained in fileName.
 * Then, it writes the decrypted message to a file with the same
 * name as fileName, but with a different suffix ".de"
 * =================
 * @param:
 * 1. fileName : The name of the huffman encoded file to be decrypted.
 * @requires:
 * 1. fileName exists and can be opened for read access.
 * 2. fileName contains the correct encoding message which would be 
 * generated by the encrypt function defined in the program.
 */
void decrypt(const char* fileName);


